# site settings
title: CA Programming
subtitle:
email: jiaxin.he@concordacademy.org
description: A club for Concord Academy students interested in <br /> computer science to learn, connect, and contribute to <br /> the community through enjoyable projects.
baseurl: "/Club-Website" # the subpath of your site, e.g. /blog
url: caprogramming.github.io # the base hostname & protocol for your site
author: Club coheads - Jake Pine, Jason He, and Wesley Lo
street_address: 166 Main Street
city: Concord
state: MA
zip_code: 01742
country: United States of America
phone: 978-402-2277

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 3

# social settings
500px_url:
facebook_url:
github_url: https://github.com/CAProgramming
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
